version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api_gateway
    environment:
      - REACT_APP_API_GATEWAY_URL=http://api_gateway:8001

  api_gateway:
    build: ./api_gateway
    ports:
      - "8001:8001"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "9000:9000"
    depends_on:
      - api_collector
      - api_collector_2
      - scraper
      - mongo_db
    environment:
      - MONGO_URL=mongodb://mongo_db:27017

  api_collector:
    build: ./api_collector
    ports:
      - "10000:10000"
    depends_on:
      - data_processor
      - mongo_db

  api_collector_2:
    build: ./api_collector_2
    ports:
      - "10001:10001"
    depends_on:
      - data_processor
      - mongo_db

  scraper:
    build: ./scraper
    ports:
      - "11000:11000"
    depends_on:
      - data_processor
      - mongo_db

  scheduler:
    build: ./scheduler
    depends_on:
      - backend
      - api_collector
      - api_collector_2
      - scraper

  data_processor:
    build: ./data_processor
    ports:
      - "13000:13000"
    depends_on:
      - mongo_db

  mongo_db:
    build: ./mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


volumes:
  mongo_data: