# Usa la imagen oficial de MongoDB
FROM mongo:6.0

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /data/db

# Expone el puerto predeterminado de MongoDB
EXPOSE 27017

# Comando para iniciar MongoDB
CMD ["mongod"]